services:
  backup:
    build: .
    command: python3 /backup/BackupDatabase.py
    volumes:
        - .:/backup
    networks:
      - n1
      - n2

networks:
  n1:
    external: true
  n2:
    external: true
